# Generated by Django 5.0.6 on 2024-08-26 17:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40)),
                ('book_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='college_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('regd_no', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=80)),
                ('section', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=30)),
                ('address', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='book_issuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('book_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.add_book')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.user_master')),
            ],
        ),
    ]
