# Generated by Django 5.0.6 on 2024-08-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issuse',
            name='date',
            field=models.DateField(),
        ),
    ]
