# Generated by Django 5.0.6 on 2024-09-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_book_issuse_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_issuse',
            old_name='student_name',
            new_name='regd_no',
        ),
    ]
